### ISSUE TITLE
`DOMException` when scrolling in iframe.

### ISSUE THREAD

**Issue by drewsilcock** [gblazex/smoothscroll#153]
**Description**: `DOMException` occurs when scrolling on an iframe in certain websites.

**Reproduction steps**:

1. Go to any website that uses Disqus, such as [this blog post](https://www.troyhunt.com/random-thoughts-on-the-use-of-breach-data/).
2. Scroll down to Disqus comments section.
3. Scroll inside the Disqus iframe.
4. Observe uncaught `DOMException`.

**Exception**:

```yaml
DOMException: Blocked a frame with origin "https://disqus.com" from accessing a cross-origin frame.
Code: 18
Name: SecurityError
Stack: Error: Blocked a frame with origin "https://disqus.com" from accessing a cross-origin frame at wheel (chrome-extension://nbokbjkabcmbfdlbddjidfmibcpneigj/src/sscr.js:345:26)
```

**Locals**:

```javascript
{
    "deltaX": 0,
    "deltaY": 120,
    "event": {
        "isTrusted": true
    },
    "target": {
        "uniqueID": 0
    },
    "xOnly": 0,
    "this": Window
}
```
